package com.loneless.controller;

enum CommandName {
    ADD_TRANSACTION, AUTHORISE_USER, DELETE_TRANSACTION, UPDATE_TRANSACTION,WRONG_REQUEST, GET_ALL_TRANSACTION,
    CALCULATE_CURRENT_SUM, RECEIVE_PLANNED_TRANSACTION
}

